### ISSUE TITLE
TreeTagger parameter file invalid: french-utf8.par  - How to fix?

### ISSUE THREAD

**Issue by GenTxt** [mbwolff/Word-Vector-Text-Inflector#1]
Hi:

Your word2vec model looks very intriguing. 

Unfortunately I'm running into the following error when testing your script

$ python transformText.py > out.txt

Traceback (most recent call last):
  File "transformText.py", line 31, in <module>
    tagger = treetaggerwrapper.TreeTagger(TAGLANG='fr')
  File "/usr/local/lib/python2.7/dist-packages/treetaggerwrapper.py", line 938, in __init__
    self._set_tagger(kargs)
  File "/usr/local/lib/python2.7/dist-packages/treetaggerwrapper.py", line 1025, in _set_tagger
    self.tagparfile)
treetaggerwrapper.TreeTaggerError: TreeTagger parameter file invalid: french-utf8.par

I've downloaded the French and English models from the website and placed them in the same treetagger folder:

export TREETAGGER_HOME=/usr/lib/treetagger/

Renamed 'french.par' to 'french-utf8.par'. Original name throws same error.

Am I using the wrong python wrapper?

treetaggerwrapper.py contains:

    },
    "fr": {
        "encoding": "utf-8",
        "tagparfile": "french-utf8.par",
        "abbrevfile": "french-abbreviations-utf8",
        "pchar": ALONEMARKS + "'",

etc.

Any suggestions are appreciated. 

Also, can this model be run on English texts?

Thanks,

**Comment by mbwolff** [comment]
Thanks for your message. I installed TreeTagger in my Python modules diectory:

wolffm0n1:~ mark$ ls -l /usr/local/lib/python2.7/site-packages/treetagger
total 23024
-rw-r-----   1 mark  admin     1133 May  4  2009 FILES
-rw-r-----   1 mark  admin     2525 Oct  1  2001 LICENSE
-rw-r-----   1 mark  admin     8471 Oct 27  2005 README
-rw-r-----   1 mark  admin     3392 Jul  3  2014 README.script
drwxr-x---   5 mark  admin      170 Sep 23  2015 bin
drwxr-x---  40 mark  admin     1360 Sep 25 00:51 cmd
drwxr-x---   4 mark  admin      136 Apr 30  1998 doc
-rw-r--r--@  1 mark  staff  8986928 Dec 18  2014 french-chunker-par-linux-3.2-utf8.bin.gz
-rw-r--r--@  1 mark  admin  2636234 Jan 11  2010 french-par-linux-3.2-utf8.bin.gz
-rwxr-xr-x@  1 mark  admin     6457 Jul  5 12:36 install-tagger.sh
drwxr-xr-x  30 mark  admin     1020 Sep 25 00:51 lib
-rw-r--r--@  1 mark  admin   123199 Mar 23  2016 tagger-scripts.tar.gz

Have you set the TAGDIR in treetaggerwrapper.py to your location of TreeTagger?

This model can’t work on English texts because the file “ARTFLmodel” was built using a corpus of over 1300 French texts and so will only transform French texts. I’ll upload the code for making ARTFLmodel to the repository but I can’t share the corpus. If you make a word2Vec model with a corpus of English texts and then modify transformText.py accordingly (for English grammar), you should get it to work.

I hope this helps.

Best,

mw

> On Dec 10, 2016, at 10:56 AM, GenTxt <notifications@github.com> wrote:
> 
> Hi:
> 
> Your word2vec model looks very intriguing.
> 
> Unfortunately I'm running into the following error when testing your script
> 
> $ python transformText.py > out.txt
> 
> Traceback (most recent call last):
> File "transformText.py", line 31, in 
> tagger = treetaggerwrapper.TreeTagger(TAGLANG='fr')
> File "/usr/local/lib/python2.7/dist-packages/treetaggerwrapper.py", line 938, in init
> self._set_tagger(kargs)
> File "/usr/local/lib/python2.7/dist-packages/treetaggerwrapper.py", line 1025, in _set_tagger
> self.tagparfile)
> treetaggerwrapper.TreeTaggerError: TreeTagger parameter file invalid: french-utf8.par
> 
> I've downloaded the French and English models from the website and placed them in the same treetagger folder:
> 
> export TREETAGGER_HOME=/usr/lib/treetagger/
> 
> Renamed 'french.par' to 'french-utf8.par'. Original name throws same error.
> 
> Am I using the wrong python wrapper?
> 
> treetaggerwrapper.py contains:
> 
> },
> "fr": {
>     "encoding": "utf-8",
>     "tagparfile": "french-utf8.par",
>     "abbrevfile": "french-abbreviations-utf8",
>     "pchar": ALONEMARKS + "'",
> 
> etc.
> 
> Any suggestions are appreciated.
> 
> Also, can this model be run on English texts?
> 
> Thanks,
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Mark B. Wolff, Ph.D.

http://markwolff.name/

**Comment by GenTxt** [comment]
Thanks for the reply. I've removed TreeTagger  and reinstalled as per your example.
How do I set the TAGDIR in treetaggerwrapper.py to the correct location? I'm new to python and this script is the most complex I've tested so far.

Thanks

**Comment by mbwolff** [comment]
I’m not sure how to set the TAGDIR but if you install TreeTagger in /usr/local/lib/python2.7/site-packages/ (or wherever you put your Python packages) it should work: this is what I did and it is a default location for treetaggerwrapper.py.

> On Dec 10, 2016, at 3:15 PM, GenTxt <notifications@github.com> wrote:
> 
> Thanks for the reply. I've removed TreeTagger and reinstalled as per your example.
> How do I set the TAGDIR in treetaggerwrapper.py to the correct location? I'm new to python and this script is the most complex I've tested so far.
> 
> Thanks
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Mark B. Wolff, Ph.D.

http://markwolff.name/

**Comment by GenTxt** [comment]
I fixed some root ownership issues for the treetagger folder and added PATH variables to .bashrc.

Everything is working fine now. Thanks
